### ISSUE TITLE
Debian 8 dependencies

### ISSUE THREAD

**Issue by thelightning87** [louwrentius/storagefancontrol#2]
Hello,

What are the Debian 8 dependencies?
Script result:

root@vod:/home# sh /usr/sbin/storagefancontrol
/usr/sbin/storagefancontrol: 6: /usr/sbin/storagefancontrol:
This program controls the chassis fan speed through PWM based on the temperature
of the hottest hard drive in the chassis. It uses the IBM M1015 or LSI tool
'MegaCli' for reading hard drive temperatures.
: not found
/usr/sbin/storagefancontrol: 7: /usr/sbin/storagefancontrol: import: not found
/usr/sbin/storagefancontrol: 8: /usr/sbin/storagefancontrol: import: not found
/usr/sbin/storagefancontrol: 9: /usr/sbin/storagefancontrol: import: not found
/usr/sbin/storagefancontrol: 10: /usr/sbin/storagefancontrol: import: not found
/usr/sbin/storagefancontrol: 11: /usr/sbin/storagefancontrol: import: not found
/usr/sbin/storagefancontrol: 12: /usr/sbin/storagefancontrol: import: not found
/usr/sbin/storagefancontrol: 13: /usr/sbin/storagefancontrol: import: not found
/usr/sbin/storagefancontrol: 14: /usr/sbin/storagefancontrol: import: not found
/usr/sbin/storagefancontrol: 15: /usr/sbin/storagefancontrol: import: not found
/usr/sbin/storagefancontrol: 16: /usr/sbin/storagefancontrol: import: not found
/usr/sbin/storagefancontrol: 18: /usr/sbin/storagefancontrol: Syntax error: "(" unexpected

Only change in config file is the change to "smart" instead of "controller"

**Comment by louwrentius** [comment]
It's python not sh :)

**Comment by thelightning87** [comment]
That explains alot. Thank you.
Unfortunately sensors-detect barely finds any compatible sensors and pwmconfig can't find anything at all. Very wierd since the motherboard (Supermicro X10SLM-F) should be widely supported.

I will drop this for now. The fan noise doesn't bother me that much anyway.

**Comment by louwrentius** [comment]
Lmsensors is not used by storagefancontrol...
Its smartmontools
